[package]
name = "core"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { workspace = true, features = ["serde-serialize"] }
rand = { version = "0.6.5", features = ["wasm-bindgen"] }
getrandom = { version = "0.2", features = ["js"] }
web-sys = { workspace = true, features = ["console"] }
js-sys = { workspace = true }
watch = { workspace = true }

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js = false
demangle-name-section = true
dwarf-debug-info = false